### ISSUE TITLE
Currency convertor and unit converter is not working well.

### ISSUE THREAD

**Issue by Finalboss77** [prathameshmm02/Calculator-inator#14]
I hope u try to detection the problem,and solve it.For not i have to use my system calculator.But if this app improve i will install it.

Thank you

**Comment by prathameshmm02** [comment]
Can you elaborate on what's wrong with the Currency converter? I've certainly fixed issues in the unit converter in the latest commit.

**Comment by prathameshmm02** [comment]
No further information. I'll close this as it's mostly fixed according to me.
