### ISSUE TITLE
Wrong percentage calculation

### ISSUE THREAD

**Issue by gdonisi** [prathameshmm02/Calculator-inator#15]
The calculation of a percentage, in certain cases, is incorrect.
If I type 20-10%, the result should be 18, but the app shows 19.9 (it just divides by 100 the number before %).

Here's a screen with your app and Google Calculator:
![pic](https://user-images.githubusercontent.com/82442402/169334734-a9fa8d6b-3f26-40a0-954e-9052251cdf6d.png)

**Comment by prathameshmm02** [comment]
Calculations are handled by [MxParser](https://github.com/mariuszgromada/MathParser.org-mXparser) so it's highly unlikely that it will change.

**Comment by prathameshmm02** [comment]
Calculations are handled by [MxParser](https://github.com/mariuszgromada/MathParser.org-mXparser) so it's highly unlikely that it will change.

**Comment by prathameshmm02** [comment]
See https://github.com/mariuszgromada/MathParser.org-mXparser/issues/83.

**Comment by gdonisi** [comment]
Ok, thanks anyway.
