### ISSUE TITLE
Certain conditions cause the app to crash

### ISSUE THREAD

**Issue by ch3thanhs** [prathameshmm02/Calculator-inator#22]
Steps to reproduce the crash -
- Go to "Time" converter.
- Change "from" to hour.
- Change "to" to minute, seconds, etc.
- Enter "1" in hours.
- Change converter type to Temperature.
- App crashes.

In some instances after the crash the app can't be opened. However, it opens if cache and storage data is cleared.

https://user-images.githubusercontent.com/76928501/172457133-805e220d-04ec-4f5f-aa65-62dd7c379b22.mp4

**Comment by prathameshmm02** [comment]
I think I might know why this is happening, I will try to fix it in the next update.

**Comment by VasilisKos** [comment]
Also, rotating to landscape and back to portrait crashes the app. At least on Android 11...

**Comment by prathameshmm02** [comment]
@VasilisKos on which screen?
