### ISSUE TITLE
If possible change it's name

### ISSUE THREAD

**Issue by Pranab009** [prathameshmm02/Calculator-inator#4]
If possible then change it's name and replaced it with open cal / open Calculator etc.
Only "Calculator" name is not enough because there are many "Calculator" named apps are available inside Fdroid.
open cal / open Calculator this names is  easily glorify and it's name that it is open source.
Think about it.

**Comment by prathameshmm02** [comment]
I've changed the name of my app to Calculator-inator. So, I'll close this. It should reflect in the new update.
