### ISSUE TITLE
inaccurate percent calculation

### ISSUE THREAD

**Issue by GunmetalOrb73** [prathameshmm02/Calculator-inator#46]
Steps to recreate:
Add any number by any percent such as 999+7%

Result:
I get 999.07

Expected result:
I expect to get 1068.93
![Screenshot_20221009-212115_Calculator-inator](https://user-images.githubusercontent.com/48606298/194789236-29432541-899a-4604-a5f9-3f5779789779.png)

**Comment by prathameshmm02** [comment]
Duplicate of #15.
